default_platform(:ios)

platform :ios do

  desc "Increment build number"
  lane :increment_build do
    build_number = ENV["GITHUB_RUN_NUMBER"] || Time.now.strftime("%Y%m%d%H%M")

    increment_build_number(
      build_number: build_number
    )
  end

  desc "Run SwiftLint"
  lane :lint do
    swiftlint
  end

  desc "Run Unit Tests"
  lane :test do
    scan(
      scheme: "SwipeAssignment",
      code_coverage: true
    )
  end

  desc "Build App"
  lane :build do
    build_app(
      scheme: "SwipeAssignment",
      skip_codesigning: true,
      skip_package_ipa: true
    )
  end

  desc "Complete CI Pipeline"
  lane :ci do
    increment_build
    lint
    test
    build
  end

end